import { execSync } from "child_process";
import fs from "node:fs";
import { beforeAll, describe, expect, test } from "vitest";

const SERVER_PATH = "./test/generated/fastmcp/server.ts";
const MCP_INSPECTOR = "bunx @modelcontextprotocol/inspector";

function runMCPCommand(method: string, toolName?: string, args?: string[]): string {
  let cmd = `${MCP_INSPECTOR} --cli bun ${SERVER_PATH} --transport stdio --method ${method}`;

  if (toolName) {
    cmd += ` --tool-name ${toolName}`;
  }

  if (args && args.length > 0) {
    cmd += ` ${args.map(arg => `--tool-arg '${arg}'`).join(' ')}`;
  }

  try {
    return execSync(cmd, { encoding: 'utf8', timeout: 15000 });
  } catch (error: any) {
    throw new Error(`MCP command failed: ${error.message}\nCommand: ${cmd}`);
  }
}

describe("FastMCP Server Tests", () => {
  beforeAll(async () => {
    // Verify server file was generated by pretest script
    if (!fs.existsSync(SERVER_PATH)) {
      throw new Error(`Server file not found at ${SERVER_PATH}. Run 'bun run pretest:server' first.`);
    }

    console.log('Server file found - running tests');
  }, 5000);

  test("should list all available tools", () => {
    const output = runMCPCommand("tools/list");
    expect(output).toContain("addPet");
    expect(output).toContain("getInventory");
    expect(output).toContain("loginUser");
  });

  describe.concurrent("Pet Operations", () => {
    test.concurrent("addPet - should accept pet object", async ({ expect }) => {
      const output = runMCPCommand("tools/call", "addPet", [
        "name=doggie",
        'photoUrls=["http://example.com/photo1.jpg"]',
        "status=available"
      ]);
      expect(output).not.toContain("error");
    });

    test.concurrent("updatePet - should accept pet object", async ({ expect }) => {
      const output = runMCPCommand("tools/call", "updatePet", [
        "id=1",
        "name=doggie-updated",
        'photoUrls=["http://example.com/photo1.jpg"]',
        "status=sold"
      ]);
      expect(output).not.toContain("error");
    });

    test.concurrent("findPetsByStatus - should accept status array", async ({ expect }) => {
      const output = runMCPCommand("tools/call", "findPetsByStatus", ['status=["available", "pending"]']);
      expect(output).not.toContain("error");
    });

    test.concurrent("getPetById - should accept petId parameter", async ({ expect }) => {
      const output = runMCPCommand("tools/call", "getPetById", ["petId=1"]);
      expect(output).not.toContain("error");
    });
  });

  describe.concurrent("Store Operations", () => {
    test.concurrent("getInventory - should work without parameters", async ({ expect }) => {
      const output = runMCPCommand("tools/call", "getInventory");
      expect(output).not.toContain("error");
    });

    test.concurrent("placeOrder - should accept order object", async ({ expect }) => {
      const orderData = JSON.stringify({
        petId: 1,
        quantity: 2,
        shipDate: "2024-01-01T00:00:00.000Z",
        status: "placed",
        complete: false
      });
      const output = runMCPCommand("tools/call", "placeOrder", [`data=${orderData}`]);
      expect(output).not.toContain("error");
    });

    test.concurrent("getOrderById - should accept orderId parameter", async ({ expect }) => {
      const output = runMCPCommand("tools/call", "getOrderById", ["orderId=1"]);
      expect(output).not.toContain("error");
    });
  });

  describe.concurrent("User Operations", () => {
    test.concurrent("createUser - should accept user object", async ({ expect }) => {
      const userData = JSON.stringify({
        username: "testuser",
        firstName: "Test",
        lastName: "User",
        email: "test@example.com",
        password: "testpass",
        phone: "123-456-7890",
        userStatus: 1
      });
      const output = runMCPCommand("tools/call", "createUser", [`data=${userData}`]);
      expect(output).not.toContain("error");
    });

    test.concurrent("loginUser - should accept username and password", async ({ expect }) => {
      const output = runMCPCommand("tools/call", "loginUser", [
        "username=testuser",
        "password=testpass"
      ]);
      expect(output).not.toContain("error");
    });

    test.concurrent("getUserByName - should accept username parameter", async ({ expect }) => {
      const output = runMCPCommand("tools/call", "getUserByName", ["username=testuser"]);
      expect(output).not.toContain("error");
    });
  });
});